fragment NavigationColumnFields on NavigationColumn {
  __typename
  sys {
    id
  }
  heading
  columnTitleLink {
    __typename
    ... on Page {
      ...PageLinkFields
    }
    ... on NavigationLink {
      ...NavigationLinkFields
    }
  }
  linksCollection(limit: 20) {
    items {
      ...PageLinkFields
    }
  }
}

fragment PageFeaturedNavFields on Page {
  ...PageLinkFields
  seo {
    image {
      ...AssetFields
    }
  }
  topSectionCollection(limit: 8) {
    items {
      ... on ComponentHeroBanner {
        image {
          ...AssetFields
        }
      }
      ... on ComponentDuplex {
        image {
          ...AssetFields
        }
      }
    }
  }
}

fragment NavigationSectionFields on NavigationSection {
  __typename
  sys {
    id
  }
  label
  sectionTitleLink {
    ...PageLinkFields
  }
  featuredLink {
    ...PageFeaturedNavFields
  }
  featuredImage {
    ...AssetFields
  }
  columnsCollection(limit: 13) {
    items {
      ...NavigationColumnFields
    }
  }
}

fragment NavigationMenuFields on NavigationMenu {
  sectionsCollection(limit: 8) {
    items {
      ...NavigationSectionFields
    }
  }
}

fragment NavigationFields on NavigationMenuCollection {
  items {
    ...NavigationMenuFields
  }
}

query CtfNavigation($locale: String, $preview: Boolean) @contentSourceMaps {
  navigationMenuCollection(locale: $locale, preview: $preview, limit: 1, order: [sys_publishedAt_DESC]) {
    ...NavigationFields
  }
}
